In [1]:
import numpy as np

In [2]:
matrix1 = np.array([(1,2,3),(7,8,9),(40,50,60),(25,75,95)])

In [3]:
matrix1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [40, 50, 60],
       [25, 75, 95]])

In [4]:
matrix2 = np.array([(7,8,9),(4,5,6),(10,20,30),(15,45,85)])

In [5]:
matrix2

array([[ 7,  8,  9],
       [ 4,  5,  6],
       [10, 20, 30],
       [15, 45, 85]])

In [6]:
matrix3 = matrix1 + matrix2

In [7]:
matrix3

array([[  8,  10,  12],
       [ 11,  13,  15],
       [ 50,  70,  90],
       [ 40, 120, 180]])

In [9]:
matrix1[:,1]

array([ 2,  8, 50, 75])

In [11]:
matrix3[matrix3 > 5]

array([  8,  10,  12,  11,  13,  15,  50,  70,  90,  40, 120, 180])

In [12]:
arr1 = np.arange(1,100,5)

In [13]:
arr1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [14]:
arr1.ndim

1

In [15]:
arr1.dtype

dtype('int32')

In [16]:
arr1.shape

(20,)

In [17]:
arr1.std()

28.83140648667699

In [18]:
arr1_sqrt = np.sqrt(arr1.std())

In [19]:
arr1_sqrt

5.3694884753277